---
name: FlashItem2
version: 1.0.0
main: DavidFlash\FlashItem\Main
api: 3.14.0

commands:
  flashitem:
    description: "Give yourself custom item!"
  openflashitem:
    description: "Open FlashItem Menu"
...
