# Configuration file for FlashItem2 originally made by David Flash

# Do you want to give the item when player joins?
enabled: true

# Item to open menu (Has to be numeric)
item: 345 #Default: 345 [Compass]

# Name of the item
name: "§l§aNavigator"

# Minigame is name that will appear in menu and chat
minigame1: Minigame
command1: say This is just a example of a command! Change this in config.yml

minigame2: Minigame2
command2: say This is just a example of a command! Change this in config.yml

minigame3: Minigame3
command3: say This is just a example of a command! Change this in config.yml

minigame4: Minigame4
command4: say This is just a example of a command! Change this in config.yml

minigame5: Minigame5
command5: say This is just a example of a command! Change this in config.yml

minigame6: Minigame6
command6: say No one was harmed during the making of this plugin 
